!!python/object/apply:collections.OrderedDict
- - [batch_size, 256]
  - [buffer_size, 1000000]
  - [ent_coef, auto]
  - [env_wrapper, utils.wrappers.TimeFeatureWrapper]
  - [gamma, 0.98]
  - [gradient_steps, 1]
  - [learning_rate, 0.0003]
  - [learning_starts, 10000]
  - [n_timesteps, 2000000.0]
  - [policy, CustomSACPolicy]
  - [tau, 0.01]
  - [train_freq, 1]
