!!python/object/apply:collections.OrderedDict
- - [batch_size, 64]
  - [buffer_size, 2000000]
  - [ent_coef, 0.005]
  - [gradient_steps, 1]
  - [learning_rate, lin_3e-4]
  - [learning_starts, 1000]
  - [n_timesteps, 30000000.0]
  - [policy, CustomSACPolicy]
  - [train_freq, 1]
