!!python/object/apply:collections.OrderedDict
- - [ent_coef, 0.000125]
  - [gamma, 0.9999]
  - [learning_rate, 0.0675]
  - [lr_schedule, constant]
  - [n_envs, 8]
  - [n_steps, 16]
  - [n_timesteps, 100000000.0]
  - [normalize, true]
  - [policy, MlpPolicy]
  - [vf_coef, 0.51]
