!!python/object/apply:collections.OrderedDict
- - [ent_coef, 0.001]
  - [gamma, 0.999]
  - [lr_schedule, linear]
  - [n_envs, 16]
  - [n_timesteps, 5000000.0]
  - [normalize, true]
  - [policy, MlpPolicy]
