!!python/object/apply:collections.OrderedDict
- - [cg_damping, 0.001]
  - [cg_iters, 10]
  - [entcoeff, 0.0]
  - [gamma, 0.99]
  - [lam, 1]
  - [max_kl, 0.001]
  - [n_timesteps, 1000000.0]
  - [policy, MlpPolicy]
  - [timesteps_per_batch, 512]
  - [vf_iters, 3]
  - [vf_stepsize, 0.0001]
