!!python/object/apply:collections.OrderedDict
- - [ent_coef, 0.001]
  - [frame_stack, 4]
  - [lr_schedule, linear]
  - [n_envs, 16]
  - [n_timesteps, 100000000.0]
  - [normalize, true]
  - [policy, MlpPolicy]
